name:
  test

on:
  push:
    branches: [ main ]

jobs:
  print-datetime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Datetime
        run: echo "Current Datetime is $(date)"
